// Generated by scripts/sync-newsletter.mjs from the Benchmarked repo. Do not edit by hand.

export type Issue = {
  slug: string;
  title: string;
  dek: string;
  /** as printed, e.g. "3 Oct 2026" */
  date: string;
  /** YYYY-MM-DD */
  iso: string;
  /** e.g. "Model launch" */
  kind: string;
  minutes?: number;
  /** the issue's first figure */
  cover?: string;
};

/** newest first */
export const issues: Issue[] = [
  {
    "slug": "2026-10-03-ai-week-roundup",
    "title": "The week Washington stepped into AI",
    "dek": "A voluntary White House accord, a reported FTC probe, Anthropic’s leaked IPO numbers and a turbulent week at OpenAI, plus where the model race stands.",
    "date": "3 Oct 2026",
    "iso": "2026-10-03",
    "kind": "Weekly roundup",
    "minutes": 7,
    "cover": "/newsletter/2026-10-03-ai-week-roundup/images/x-whitehouse.jpg"
  },
  {
    "slug": "2026-10-01-claude-fable-5-5",
    "title": "Is Claude Fable 5.5 already here?",
    "dek": "Anthropic hasn’t announced it. Some users say chats labelled Fable 5.1 are behaving like a newer model, but the name, the quality and the release date are all unconfirmed.",
    "date": "1 Oct 2026",
    "iso": "2026-10-01",
    "kind": "Rumor check",
    "minutes": 6,
    "cover": "/newsletter/2026-10-01-claude-fable-5-5/images/lead-chet-label-51.jpg"
  },
  {
    "slug": "2026-09-30-meta-muse",
    "title": "Meta’s Muse: the most polished consumer agent yet, after a rough first three weeks",
    "dek": "A free tier took Muse to #1 on both app stores. The model is mid-pack, and launch brought an Amazon block, a privacy dispute and a patched Mac flaw.",
    "date": "30 Sep 2026",
    "iso": "2026-09-30",
    "kind": "Product launch",
    "minutes": 6,
    "cover": "/newsletter/2026-09-30-meta-muse/images/lead-muse-secure-vm.jpg"
  },
  {
    "slug": "2026-09-30-gemini-4-argon",
    "title": "Gemini 4 Argon: is Google back on top?",
    "dek": "Google's own chart says it wins 12 of 18 benchmarks. Independent testers say it's top-tier, but not the best, and almost nobody can use it yet.",
    "date": "30 Sep 2026",
    "iso": "2026-09-30",
    "kind": "Model launch",
    "minutes": 6,
    "cover": "/newsletter/2026-09-30-gemini-4-argon/images/web-google-keyart.jpg"
  },
  {
    "slug": "2026-09-29-openai-devday-2026",
    "title": "OpenAI DevDay 2026: three launches that matter, and a catch",
    "dek": "Always-on agents, a cheap near-flagship model and an up-to-8× speed tier led more than 20 announcements. Independent tests call the model a value pick, not the smartest, and the $200 plan shrank.",
    "date": "29 Sep 2026",
    "iso": "2026-09-29",
    "kind": "Event recap",
    "minutes": 6,
    "cover": "/newsletter/2026-09-29-openai-devday-2026/images/keynote-slide.jpg"
  },
  {
    "slug": "2026-09-28-claude-sonnet-5-5",
    "title": "Claude Sonnet 5.5: near-Opus scores at half the token price",
    "dek": "Independent tests confirm it sits two points behind Opus 5.5. The catch: at max effort it writes more output tokens per task than any model Artificial Analysis has measured.",
    "date": "28 Sep 2026",
    "iso": "2026-09-28",
    "kind": "Model launch",
    "minutes": 6,
    "cover": "/newsletter/2026-09-28-claude-sonnet-5-5/images/web-anthropic-hero.jpg"
  },
  {
    "slug": "2026-09-25-jev-typesafe-ai",
    "title": "Jev: the AI model that can’t write a sentence",
    "dek": "TypeSafe AI’s new model only makes typed decisions, fast and very cheaply. Early independent tests back the speed and cost, but its accuracy looks like a good small model’s, and it always answers, even when it shouldn’t.",
    "date": "25 Sep 2026",
    "iso": "2026-09-25",
    "kind": "Product launch",
    "minutes": 6,
    "cover": "/newsletter/2026-09-25-jev-typesafe-ai/images/llm-vs-jev.jpg"
  },
  {
    "slug": "2026-09-24-claude-opus-5-5",
    "title": "Claude Opus 5.5: a narrow lead at a lower price",
    "dek": "Independent leaderboards put Anthropic’s new mid-priced model first, but the margin shrinks outside Anthropic’s own tests, and at max effort the token bill climbs fast.",
    "date": "24 Sep 2026",
    "iso": "2026-09-24",
    "kind": "Model launch",
    "minutes": 6,
    "cover": "/newsletter/2026-09-24-claude-opus-5-5/images/web-anthropic-hero.jpg"
  }
];
