// Generated by scripts/bake-creatures.py. Do not edit by hand.
// Texture extents in swimmer body units (snout at x = +100, 210 per body length).
export const ATLAS = {
  "whale": {
    "x0": -124.0,
    "x1": 104.0,
    "y0": -62.0,
    "y1": 62.0,
    "w": 1536,
    "h": 832
  },
  "shark": {
    "x0": -114.0,
    "x1": 104.0,
    "y0": -47.0,
    "y1": 47.0,
    "w": 896,
    "h": 384
  },
  "fish": {
    "x0": -114.0,
    "x1": 104.0,
    "y0": -38.0,
    "y1": 38.0,
    "w": 320,
    "h": 112
  }
} as const;
