"""
Packs the Blender renders of the voyage intro's sea creatures into the
textures the engine reads. The models themselves are built and rendered by
scripts/blender/sea_creatures.py; this script runs it, then for each animal
writes:

  public/voyage/<kind>-albedo.webp  rgb skin colour under soft overhead light
                                    (so occlusion is baked in), a coverage
  public/voyage/<kind>-shape.webp   rg surface normal in the body frame, b 0,
                                    a 1 (the engine lights the body with it)

and components/voyage/creature-atlas.ts with each texture's extent in swimmer
body units. Run from the repo root:

  python3 scripts/bake-creatures.py [--skip-render]

Needs Blender on the PATH (5.x), plus numpy and Pillow. The skin uses two
Poly Haven CC0 normal maps (leather_red_02, leather_white), downloaded once
into the working folder below.
"""

import json
import os
import subprocess
import sys
import urllib.request

import numpy as np
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..")
WORK = os.path.expanduser("~/Projects/portfolio-projects/_blender")
RENDERS = os.path.join(WORK, "renders")
TEXTURES = os.path.join(WORK, "textures")
OUT = os.path.join(ROOT, "public", "voyage")
POLYHAVEN = {
    "leather_red_02_nor_gl_1k.jpg": "https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/leather_red_02/leather_red_02_nor_gl_1k.jpg",
    "leather_white_nor_gl_1k.jpg": "https://dl.polyhaven.org/file/ph-assets/Textures/jpg/1k/leather_white/leather_white_nor_gl_1k.jpg",
}
EXTENTS = {
    "whale": (-124.0, 104.0, -62.0, 62.0),
    "shark": (-114.0, 104.0, -47.0, 47.0),
    "fish": (-114.0, 104.0, -38.0, 38.0),
}


def render():
    os.makedirs(TEXTURES, exist_ok=True)
    for name, url in POLYHAVEN.items():
        path = os.path.join(TEXTURES, name)
        if not os.path.exists(path):
            urllib.request.urlretrieve(url, path)
    subprocess.run(
        ["blender", "-b", "--factory-startup", "--python",
         os.path.join(ROOT, "scripts", "blender", "sea_creatures.py"), "--", RENDERS, TEXTURES],
        check=True,
    )


def pack(kind):
    # Blender's image rows run +y up; the engine's run +y down
    lit = Image.open(os.path.join(RENDERS, f"{kind}-lit.png")).convert("RGBA").transpose(Image.FLIP_TOP_BOTTOM)
    nor = Image.open(os.path.join(RENDERS, f"{kind}-normal.png")).convert("RGBA").transpose(Image.FLIP_TOP_BOTTOM)
    a = np.asarray(lit, np.float32) / 255
    n = np.asarray(nor, np.float32) / 255
    alpha = a[..., 3]
    shape = np.zeros_like(n)
    shape[..., 0] = n[..., 0]
    shape[..., 1] = n[..., 1]
    shape[..., 3] = 1
    # flat normals outside the body so mipmaps don't bleed tilt into the edge
    empty = alpha < 0.01
    shape[empty] = [0.5, 0.5, 0, 1]
    rgba = a.copy()
    rgba[empty, :3] = 0
    os.makedirs(OUT, exist_ok=True)
    Image.fromarray((rgba * 255 + 0.5).astype(np.uint8), "RGBA").save(
        os.path.join(OUT, f"{kind}-albedo.webp"), quality=90, method=6, alpha_quality=100
    )
    Image.fromarray((shape * 255 + 0.5).astype(np.uint8), "RGBA").save(
        os.path.join(OUT, f"{kind}-shape.webp"), quality=92, method=6, alpha_quality=100
    )
    x0, x1, y0, y1 = EXTENTS[kind]
    print(kind, lit.width, "x", lit.height)
    return {"x0": x0, "x1": x1, "y0": y0, "y1": y1, "w": lit.width, "h": lit.height}


if __name__ == "__main__":
    if "--skip-render" not in sys.argv:
        render()
    meta = {k: pack(k) for k in EXTENTS}
    ts = os.path.join(ROOT, "components", "voyage", "creature-atlas.ts")
    with open(ts, "w") as f:
        f.write("// Generated by scripts/bake-creatures.py. Do not edit by hand.\n")
        f.write("// Texture extents in swimmer body units (snout at x = +100, 210 per body length).\n")
        f.write("export const ATLAS = " + json.dumps(meta, indent=2) + " as const;\n")
